name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 0) Repo
      - uses: actions/checkout@v4

      # 1) Node 20 (bez pnpm cache)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2) pnpm 10 + cache
      - uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
          run_install: false
          cache: true          # <-- pnpm store bude cachován

      # 3) Build env proměnné pro Next.js
      - name: Export Firebase env vars
        run: |
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}"             >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}"     >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}"       >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}"               >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}"   >> $GITHUB_ENV

      # 4) Instalace a build front-endu
      - run: pnpm install --frozen-lockfile && pnpm --filter frontend run build

      # 5) Deploy na produkční kanál „live“
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken:              ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_METRICS_HUB_C0JVL }}
          channelId: live
          projectId: metrics-hub-c0jvl
